spring.application.name=todo-backend

# MongoDB Atlas Connection String (injected via environment variable in deployment)
# Password special characters must be URL-encoded (@ -> %40)
spring.data.mongodb.uri=mongodb+srv://krishankant1999hzb_db_user:Ad7K5XzUtLkD32eG@kant.cjotrva.mongodb.net/tododb?retryWrites=true&w=majority&appName=kant
spring.data.mongodb.database=tododb
# JWT Configuration (must be at least 256-bit / 32 characters long)
app.jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
app.jwt.expiration-ms=86400000

# Server Port
server.port=${PORT:8080}